# Generated by Django 5.0.4 on 2026-07-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employeehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('encashable_leave_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('leave_encashment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notice_period_shortfall_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('notice_penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_pending_dues', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('asset_damage_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_settlement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending HR Review'), ('APPROVED', 'Approved for Final Payout'), ('PAID', 'Settlement Disbursed')], default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_settlement', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Computation'), ('PROCESSED', 'Processed & Pending Review'), ('APPROVED', 'Approved by HR'), ('PAID', 'Disbursed to Bank')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('component_type', models.CharField(choices=[('BONUS', 'Performance Bonus'), ('INCENTIVE', 'Sales Incentive'), ('ARREARS', 'Back-Pay Arrears'), ('REIMBURSEMENT', 'Tax-Free Reimbursement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_components', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enable_pf', models.BooleanField(default=True)),
                ('pf_percentage', models.DecimalField(decimal_places=2, default=12.0, max_digits=4)),
                ('enable_esi', models.BooleanField(default=False)),
                ('esi_percentage', models.DecimalField(decimal_places=2, default=0.75, max_digits=4)),
                ('tds_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_month_days', models.PositiveIntegerField(default=30)),
                ('lop_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('worked_days', models.DecimalField(decimal_places=1, default=30.0, max_digits=4)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earned_basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earned_hra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earned_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('arrears', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pf_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('esi_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll_management.payrollbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employee.employee')),
            ],
            options={
                'unique_together': {('batch', 'employee')},
            },
        ),
    ]
