# Generated by Django 5.0.4 on 2026-07-10 05:51

import django.db.models.deletion
import employee.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[employee.validators.validate_numeric_phone])),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[employee.validators.validate_non_negative])),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.designation')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Resume', 'Resume'), ('Aadhaar', 'Aadhaar'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Offer Letter', 'Offer Letter'), ('Experience Certificate', 'Experience Certificate')], max_length=30)),
                ('document', models.FileField(upload_to='employee_docs/', validators=[employee.validators.validate_document_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_data', models.JSONField(blank=True, default=dict, null=True)),
                ('new_data', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='employee.employee')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[employee.validators.validate_non_negative])),
                ('effective_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='employee.employee')),
                ('new_designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='new_promotions', to='employee.designation')),
                ('old_designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='old_promotions', to='employee.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('notice_period', models.IntegerField(default=30)),
                ('last_working_day', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('termination_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='employee.employee')),
                ('terminated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='employee.employee')),
                ('new_department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='new_transfers', to='employee.department')),
                ('new_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_managed_transfers', to='employee.employee')),
                ('old_department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='old_transfers', to='employee.department')),
                ('old_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_managed_transfers', to='employee.employee')),
            ],
        ),
    ]
