# Generated by Django 5.0.4 on 2026-07-10 14:34

import django.db.models.deletion
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employeehistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='employeehistory',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='last_working_day',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='termination',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='termination',
            name='terminated_by',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='new_manager',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='old_manager',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='reason',
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='document_name',
            field=models.CharField(default='Placeholder Document', max_length=100),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(default='placeholder.pdf', upload_to='employee_vault/', validators=[employee.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='performed_by_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='notice_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='submission_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='termination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='termination',
            name='severance_package',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='action',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='new_designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.designation'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='new_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='old_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.designation'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='old_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resignation', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved/Processed'), ('Rejected', 'Rejected/Retained')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='new_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.department'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='old_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employee.department'),
        ),
    ]
