# Generated by Django 5.0.4 on 2026-07-31 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employeehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_feedback', models.TextField(blank=True, null=True)),
                ('self_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('manager_feedback', models.TextField(blank=True, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('performance_band', models.CharField(blank=True, choices=[('EXCEEDS', 'Exceeds Expectations'), ('MEETS', 'Meets Expectations'), ('NEEDS_IMPROVEMENT', 'Needs Improvement')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING_SELF', 'Pending Self Review'), ('SUBMITTED_SELF', 'Self Review Submitted / Pending Manager'), ('COMPLETED', 'Completed & Scored'), ('CALIBRATED', 'Calibrated by HR')], default='PENDING_SELF', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employee.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='performance_management.appraisalcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('kpi_metric', models.TextField(help_text='Measurable target, e.g., Response time < 200ms')),
                ('weightage', models.DecimalField(decimal_places=2, help_text='Percentage weightage e.g., 30.00 for 30%', max_digits=5)),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employee.employee')),
            ],
        ),
    ]
