# Generated by Django 5.0.4 on 2026-08-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='manager_rating',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='self_rating',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='kpi_metric',
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('PENDING_SELF', 'Pending Self Review'), ('SUBMITTED_SELF', 'Self Review Submitted'), ('COMPLETED', 'Completed & Scored'), ('CALIBRATED', 'Calibrated by HR')], default='PENDING_SELF', max_length=25),
        ),
        migrations.AlterField(
            model_name='goal',
            name='weightage',
            field=models.DecimalField(decimal_places=2, help_text='Weightage percentage e.g., 30.00', max_digits=5),
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_value', models.CharField(help_text='e.g., Response time < 200ms or 95% resolution', max_length=100)),
                ('achieved_value', models.CharField(blank=True, max_length=100, null=True)),
                ('is_met', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='performance_management.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('SELF', 'Self Rating'), ('MANAGER', 'Manager Rating'), ('HR', 'HR Rating')], max_length=10)),
                ('score', models.DecimalField(decimal_places=2, help_text='Rating score e.g., 4.50 out of 5.0', max_digits=3)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance_management.appraisal')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance_management.kpi')),
            ],
        ),
    ]
