# Generated by Django 5.0.4 on 2026-07-23 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employeehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('max_days_per_year', models.DecimalField(decimal_places=1, default=12.0, max_digits=5)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('is_encashable', models.BooleanField(default=False)),
                ('enable_sandwich_policy', models.BooleanField(default=False)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompOffClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending HR Review'), ('APPROVED', 'Approved and Credited'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_claims', to='employee.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_span', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('FIRST_HALF', 'Half Day - First Half'), ('SECOND_HALF', 'Half Day - Second Half')], default='FULL_DAY', max_length=20)),
                ('calculated_days', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('sandwiched_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('PENDING_L1', 'Pending Level 1 Manager Review'), ('PENDING_L2', 'Pending Level 2 HR Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCEL_REQUESTED', 'Cancellation Requested'), ('CANCELLED', 'Cancelled')], default='PENDING_L1', max_length=20)),
                ('level1_approved_at', models.DateTimeField(blank=True, null=True)),
                ('level2_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employee.employee')),
                ('level1_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('level2_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveEncashment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_encash', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending HR Review'), ('APPROVED', 'Approved for Payroll'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encashment_requests', to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('allocated', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('used', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('pending', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
