# Generated by Django 5.0.4 on 2026-07-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_options_alter_employeehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('grace_in_minutes', models.PositiveIntegerField(default=15)),
                ('grace_out_minutes', models.PositiveIntegerField(default=15)),
                ('overtime_after_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotatingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_name', models.CharField(max_length=100)),
                ('rotation_type', models.CharField(choices=[('Morning -> Evening', 'Morning to Evening Transition'), ('Evening -> Night', 'Evening to Night Transition'), ('Weekly Rotation', 'Cycles Weekly'), ('Monthly Rotation', 'Cycles Monthly')], max_length=30)),
                ('rotation_start', models.DateField()),
                ('rotation_end', models.DateField(blank=True, null=True)),
                ('next_rotation_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('maximum_daily_overtime', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('maximum_weekly_overtime', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('active', models.BooleanField(default=True)),
                ('applicable_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_rules', to='shift_management.shift')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_shifts', to='employee.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('Permanent', 'Permanent Structural Shift'), ('Temporary', 'Temporary Coverage Shift'), ('Weekly', 'Weekly Schedule Variant')], default='Permanent', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Currently Operational'), ('Expired', 'Past Effective Window')], default='Active', max_length=15)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employee.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shift_management.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Awaiting Verification Review'), ('Approved', 'Formally Executed and Completed'), ('Rejected', 'Denied by Processing Authority'), ('Cancelled', 'Retracted by Originating Staff')], default='Pending', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employee.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='employee.employee')),
                ('requester_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shift_management.shiftassignment')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='employee.employee')),
                ('target_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shift_management.shiftassignment')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='employee.employee')),
                ('friday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
                ('monday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
                ('saturday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
                ('sunday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
                ('thursday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
                ('tuesday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
                ('wednesday_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shift_management.shift')),
            ],
        ),
    ]
